site_name: Android SMS Gateway
site_url: https://sms.capcom.me
repo_url: https://github.com/capcom6/android-sms-gateway
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Local Server: getting-started/local-server.md
      - Public Cloud Server: getting-started/public-cloud-server.md
      - Private Server: getting-started/private-server.md
      - Custom Gateway Setup: getting-started/custom-gateway.md
  - API: api.md
  - Pricing: pricing.md
  - Privacy:
      - Policy: privacy/policy.md
      - Encryption: privacy/encryption.md
  - FAQ:
      - General: faq/general.md
      - Errors: faq/errors.md
  - Contributing: contributing.md
  - License: license.md
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
plugins:
  - search
  - render_swagger
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - social
