groups:
  - name: worker-alerts
    rules:
      - alert: WorkerTaskFailure
        expr: sum(rate(worker_executor_task_result_total{result="error"}[5m])) > 1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High worker task failure rate"
          description: "Worker task error rate is {{ $value }} errors per minute, exceeding threshold"
          runbook: "Check worker logs for task failures"
      - alert: LongRunningTask
        expr: histogram_quantile(0.95, sum(rate(worker_executor_task_duration_seconds_bucket[5m])) by (le)) > 30
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Worker tasks running longer than expected"
          description: "95th percentile task duration is {{ $value }}s, above 30s threshold"
          runbook: "Review task performance and optimize if needed"
      - alert: HighActiveTasks
        expr: worker_executor_active_tasks > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active worker tasks"
          description: "Active tasks count is {{ $value }}, exceeding 10 for more than 5 minutes"
          runbook: "Monitor for potential task queuing or performance issues"
