{{- if .Values.config.unsecure.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-gateway-server.fullname" . }}-config
  labels:
  # ...
data:
  config.yml: |
    {{ .Values.config.unsecure.configYml | nindent 4 }}
{{- end }}