apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-gateway-server.fullname" . }}
  labels:
    {{- include "sms-gateway-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sms-gateway-server.selectorLabels" . | nindent 4 }}
