name: Release Charts

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Bump Chart.yaml
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          CHART_FILE=deployments/kubernetes/Chart.yaml

          # Extract current version
          CURRENT_VERSION=$(awk '/^version:/ {print $2}' $CHART_FILE)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Increment patch
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          # Update Chart.yaml
          sed -i "s/^version:.*/version: $NEW_VERSION/" $CHART_FILE
          sed -i "s/^appVersion:.*/appVersion: $TAG_VERSION/" $CHART_FILE

          # Commit and push changes
          git add $CHART_FILE
          git commit -m "[infra] bump Chart version to $NEW_VERSION and appVersion to $TAG_VERSION"
          git push origin HEAD:master
