name: docker-build

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true
    outputs:
      app-version:
        value: ${{ jobs.build.outputs.app-version }}

jobs:
  build:
    name: Docker image
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' # skip on dependabot because it's not allowed to access secrets
    permissions:
      contents: read
    outputs:
      app-version: ${{ steps.releaser.outputs.metadata.tag }}
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Set APP_RELEASE env
        run: echo APP_RELEASE=$(( ($(date +%s) - $(date -d "2022-06-15" +%s)) / 86400 )) >> ${GITHUB_ENV}

      - name: Run GoReleaser
        id: releaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_RELEASE_ID: ${{ env.APP_RELEASE }}
