name: Publish Helm Chart to S3

on:
  push:
    branches:
      - master
    paths:
      - "deployments/helm-chart/**"
  release:
    types: [published]

  workflow_dispatch:

# Required permissions for the workflow
permissions:
  contents: read # for actions/checkout

concurrency:
  group: helm-publish
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint deployments/helm-chart

      - name: Install helm-s3 plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Package Helm chart
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            RAW_TAG="${{ github.event.release.tag_name }}"
            CHART_VERSION="${RAW_TAG#v}"
            APP_VERSION="${RAW_TAG#v}"
          else
            CHART_VERSION="0.0.0-$(git rev-parse --short HEAD)"
            APP_VERSION="latest"
          fi
          helm package deployments/helm-chart --version "${CHART_VERSION}" --app-version "${APP_VERSION}"

      - name: Initialize S3 repository
        run: |
          if ! helm repo list | grep s3-repo; then
            helm repo add s3-repo s3://${{ secrets.AWS_BUCKET }}/charts
          fi

      - name: Push Helm chart to S3
        run: |
          helm s3 push server-*.tgz s3-repo

      - name: Clean up
        run: |
          rm -f server-*.tgz index.yaml
